package com.uheroes.mod.core.flux;

import net.minecraft.nbt.CompoundTag;

/**
 * Neural Flux - Bio-electric energy generated by enhanced physiology
 * and amplified through the Nano-Tech suit.
 */
public class NeuralFlux {

    public static final String NBT_CURRENT        = "CurrentFlux";
    public static final String NBT_MAX            = "MaxFlux";
    public static final String NBT_REGEN_RATE     = "RegenRate";
    public static final String NBT_REGEN_COOLDOWN = "RegenCooldown";

    public static final int   DEFAULT_MAX_FLUX             = 100;
    public static final float DEFAULT_REGEN_RATE           = 2.0f;  // flux per second
    public static final int   DEFAULT_REGEN_COOLDOWN_TICKS = 40;

    private int   currentFlux;
    private int   maxFlux;
    private float regenRate;
    private int   regenCooldown;
    private boolean overcharged;

    // Fractional accumulator — prevents ceil() rounding error from making regen 10x too fast
    private float regenAccumulator = 0f;

    public NeuralFlux() {
        this.currentFlux  = DEFAULT_MAX_FLUX; // Start full so abilities work immediately
        this.maxFlux      = DEFAULT_MAX_FLUX;
        this.regenRate    = DEFAULT_REGEN_RATE;
        this.regenCooldown = 0;
        this.overcharged  = true;
    }

    public boolean consumeFlux(int amount) {
        if (currentFlux >= amount) {
            currentFlux -= amount;
            regenCooldown = DEFAULT_REGEN_COOLDOWN_TICKS;
            updateOverchargedState();
            return true;
        }
        return false;
    }

    public void addFlux(int amount) {
        currentFlux = Math.min(currentFlux + amount, maxFlux);
        updateOverchargedState();
    }

    public void tick() {
        if (regenCooldown > 0) {
            regenCooldown--;
            return; // No regen during cooldown
        }

        if (currentFlux < maxFlux) {
            // Accumulate fractional flux — avoids ceil() making 0.1/tick → 1/tick
            regenAccumulator += regenRate / 20.0f;
            if (regenAccumulator >= 1.0f) {
                int toAdd = (int) regenAccumulator;
                regenAccumulator -= toAdd;
                currentFlux = Math.min(currentFlux + toAdd, maxFlux);
            }
        } else {
            regenAccumulator = 0f; // Reset when full
        }

        updateOverchargedState();
    }

    public float getFluxPercent() {
        return maxFlux > 0 ? (float) currentFlux / maxFlux : 0.0f;
    }

    public void saveNBT(CompoundTag tag) {
        tag.putInt(NBT_CURRENT, currentFlux);
        tag.putInt(NBT_MAX, maxFlux);
        tag.putFloat(NBT_REGEN_RATE, regenRate);
        tag.putInt(NBT_REGEN_COOLDOWN, regenCooldown);
    }

    public void loadNBT(CompoundTag tag) {
        this.currentFlux   = tag.contains(NBT_CURRENT)        ? tag.getInt(NBT_CURRENT)        : DEFAULT_MAX_FLUX;
        this.maxFlux       = tag.contains(NBT_MAX)            ? tag.getInt(NBT_MAX)            : DEFAULT_MAX_FLUX;
        this.regenRate     = tag.contains(NBT_REGEN_RATE)     ? tag.getFloat(NBT_REGEN_RATE)   : DEFAULT_REGEN_RATE;
        this.regenCooldown = tag.contains(NBT_REGEN_COOLDOWN) ? tag.getInt(NBT_REGEN_COOLDOWN) : 0;
        this.regenAccumulator = 0f; // Transient, OK to reset on load
        updateOverchargedState();
    }

    public void copyFrom(NeuralFlux source) {
        this.currentFlux      = source.currentFlux;
        this.maxFlux          = source.maxFlux;
        this.regenRate        = source.regenRate;
        this.regenCooldown    = source.regenCooldown;
        this.overcharged      = source.overcharged;
        this.regenAccumulator = source.regenAccumulator;
    }

    private void updateOverchargedState() {
        this.overcharged = currentFlux >= maxFlux;
    }

    // ── Getters ───────────────────────────────────────────────────────────────
    public int     getCurrentFlux()  { return currentFlux; }
    public int     getMaxFlux()      { return maxFlux; }
    public float   getRegenRate()    { return regenRate; }
    public int     getRegenCooldown(){ return regenCooldown; }
    public boolean isOvercharged()   { return overcharged; }

    // ── Setters ───────────────────────────────────────────────────────────────
    public void setCurrentFlux(int v)    { this.currentFlux = Math.max(0, Math.min(v, maxFlux)); updateOverchargedState(); }
    public void setMaxFlux(int v)        { this.maxFlux = Math.max(1, v); this.currentFlux = Math.min(currentFlux, maxFlux); updateOverchargedState(); }
    public void setRegenRate(float v)    { this.regenRate = Math.max(0f, v); }
    public void setRegenCooldown(int v)  { this.regenCooldown = Math.max(0, v); }
}