package com.uheroes.mod.core.flux;

import net.minecraft.nbt.CompoundTag;

/**
 * Neural Flux - Bio-electric energy generated by enhanced physiology and amplified through Nano-Tech suit.
 * This is a sci-fi energy source, NOT magic or cursed energy.
 */
public class NeuralFlux {
    // NBT Keys
    public static final String NBT_CURRENT = "CurrentFlux";
    public static final String NBT_MAX = "MaxFlux";
    public static final String NBT_REGEN_RATE = "RegenRate";
    public static final String NBT_REGEN_COOLDOWN = "RegenCooldown";
    
    // Default Values
    public static final int DEFAULT_MAX_FLUX = 100;
    public static final float DEFAULT_REGEN_RATE = 2.0f;
    public static final int DEFAULT_REGEN_COOLDOWN_TICKS = 40;
    
    private int currentFlux;
    private int maxFlux;
    private float regenRate;
    private int regenCooldown;
    private boolean overcharged;
    
    public NeuralFlux() {
        this.currentFlux = 0;
        this.maxFlux = DEFAULT_MAX_FLUX;
        this.regenRate = DEFAULT_REGEN_RATE;
        this.regenCooldown = 0;
        this.overcharged = false;
    }
    
    /**
     * Attempts to consume the specified amount of flux.
     * @param amount The amount of flux to consume
     * @return true if consumption was successful, false if insufficient flux
     */
    public boolean consumeFlux(int amount) {
        if (currentFlux >= amount) {
            currentFlux -= amount;
            regenCooldown = DEFAULT_REGEN_COOLDOWN_TICKS;
            updateOverchargedState();
            return true;
        }
        return false;
    }
    
    /**
     * Adds flux to the current amount, capped at maximum.
     * @param amount The amount of flux to add
     */
    public void addFlux(int amount) {
        currentFlux = Math.min(currentFlux + amount, maxFlux);
        updateOverchargedState();
    }
    
    /**
     * Ticks the flux system, handling regeneration cooldown and passive regeneration.
     * Should be called every game tick (20 times per second).
     */
    public void tick() {
        if (regenCooldown > 0) {
            regenCooldown--;
        }
        
        if (regenCooldown <= 0 && currentFlux < maxFlux) {
            float regenPerTick = regenRate / 20.0f;
            currentFlux = Math.min(currentFlux + (int) Math.ceil(regenPerTick), maxFlux);
        }
        
        updateOverchargedState();
    }
    
    /**
     * Gets the current flux as a percentage of maximum.
     * @return A value between 0.0 and 1.0
     */
    public float getFluxPercent() {
        return maxFlux > 0 ? (float) currentFlux / maxFlux : 0.0f;
    }
    
    /**
     * Saves flux data to NBT.
     * @param tag The NBT tag to save to
     */
    public void saveNBT(CompoundTag tag) {
        tag.putInt(NBT_CURRENT, currentFlux);
        tag.putInt(NBT_MAX, maxFlux);
        tag.putFloat(NBT_REGEN_RATE, regenRate);
        tag.putInt(NBT_REGEN_COOLDOWN, regenCooldown);
    }
    
    /**
     * Loads flux data from NBT with default fallbacks.
     * @param tag The NBT tag to load from
     */
    public void loadNBT(CompoundTag tag) {
        this.currentFlux = tag.contains(NBT_CURRENT) ? tag.getInt(NBT_CURRENT) : 0;
        this.maxFlux = tag.contains(NBT_MAX) ? tag.getInt(NBT_MAX) : DEFAULT_MAX_FLUX;
        this.regenRate = tag.contains(NBT_REGEN_RATE) ? tag.getFloat(NBT_REGEN_RATE) : DEFAULT_REGEN_RATE;
        this.regenCooldown = tag.contains(NBT_REGEN_COOLDOWN) ? tag.getInt(NBT_REGEN_COOLDOWN) : 0;
        updateOverchargedState();
    }
    
    /**
     * Deep copies flux data from another NeuralFlux instance.
     * Used for death/respawn scenarios.
     * @param source The source NeuralFlux to copy from
     */
    public void copyFrom(NeuralFlux source) {
        this.currentFlux = source.currentFlux;
        this.maxFlux = source.maxFlux;
        this.regenRate = source.regenRate;
        this.regenCooldown = source.regenCooldown;
        this.overcharged = source.overcharged;
    }
    
    /**
     * Updates the overcharged state based on current flux.
     */
    private void updateOverchargedState() {
        this.overcharged = currentFlux >= maxFlux;
    }
    
    // Getters
    public int getCurrentFlux() {
        return currentFlux;
    }
    
    public int getMaxFlux() {
        return maxFlux;
    }
    
    public float getRegenRate() {
        return regenRate;
    }
    
    public int getRegenCooldown() {
        return regenCooldown;
    }
    
    public boolean isOvercharged() {
        return overcharged;
    }
    
    // Setters
    public void setCurrentFlux(int currentFlux) {
        this.currentFlux = Math.max(0, Math.min(currentFlux, maxFlux));
        updateOverchargedState();
    }
    
    public void setMaxFlux(int maxFlux) {
        this.maxFlux = Math.max(1, maxFlux);
        this.currentFlux = Math.min(this.currentFlux, this.maxFlux);
        updateOverchargedState();
    }
    
    public void setRegenRate(float regenRate) {
        this.regenRate = Math.max(0.0f, regenRate);
    }
    
    public void setRegenCooldown(int regenCooldown) {
        this.regenCooldown = Math.max(0, regenCooldown);
    }
}
